apiVersion: v2
appVersion: 0.0.1
name: prometheus-remotewrite
description: Hold remote write configuration for prometheus.
home: https://github.com/giantswarm/prometheus-remotewrite-app
version: 0.0.0-dev
annotations:
  application.giantswarm.io/team: "atlas"
  config.giantswarm.io/version: "prometheus-remotewrite"
