apiVersion: v2
appVersion: 0.0.1

name: prometheus-remotewrite

description: Hold remote write configuration for prometheus.

home: https://github.com/giantswarm/prometheus-remotewrite-app

# If you have an icon/logo, you should add it to https://github.com/giantswarm/web-assets
# and set the final URL as a value here and uncomment.
#icon: https://s.giantswarm.io/app-icons/example-app/1/light.svg

version: 0.0.0-dev
annotations:
  application.giantswarm.io/team: "atlas"
  config.giantswarm.io/version: "prometheus-remotewrite"
