apiVersion: v2
appVersion: 0.0.1
name: prometheus-remotewrite
description: Hold remote write configuration for prometheus.
home: https://github.com/giantswarm/prometheus-remotewrite
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
version: 1.4.1
annotations:
  io.giantswarm.application.team: "atlas"
dependencies:
  - name: kube-prometheus-stack
    alias: kubePrometheusStack
    version: 19.0.2
    repository: https://giantswarm.github.io/default-catalog/
    condition: kubePrometheusStack.enabled
