apiVersion: v2
appVersion: 0.0.1
name: prometheus-remotewrite
description: Hold remote write configuration for prometheus.
home: https://github.com/giantswarm/prometheus-remotewrite-app
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
version: 0.2.0
annotations:
  application.giantswarm.io/team: "atlas"
  config.giantswarm.io/version: 1.x.x
