{{- if .Values.remoteWrite.mimir.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-mimir-to-grafana-cloud
  namespace: mimir
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: prometheus
      controlledValues: RequestsAndLimits
      minAllowed:
        cpu: {{ .Values.remoteWrite.mimir.prometheus.vpa.minAllowed.cpu }}
        memory: {{ .Values.remoteWrite.mimir.prometheus.vpa.minAllowed.memory }}
      maxAllowed:
        cpu: {{ .Values.remoteWrite.mimir.prometheus.vpa.maxAllowed.cpu }}
        memory: {{ .Values.remoteWrite.mimir.prometheus.vpa.maxAllowed.memory }}
      mode: Auto
  targetRef:
    apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    name: mimir-to-grafana-cloud
  updatePolicy:
    updateMode: Auto
{{- end }}
