version: 2.1

orbs:
  architect: giantswarm/architect@5.1.1

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: app-catalog
          context: architect
          executor: app-build-suite
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          chart: prometheus-remotewrite
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: aws-app-collection
          context: architect
          app_name: prometheus-remotewrite
          app_namespace: monitoring
          app_collection_repo: aws-app-collection
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: azure-app-collection
          context: architect
          app_name: prometheus-remotewrite
          app_namespace: monitoring
          app_collection_repo: azure-app-collection
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: vsphere-app-collection
          context: architect
          app_name: prometheus-remotewrite
          app_namespace: monitoring
          app_collection_repo: vsphere-app-collection
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-cloud-director-app-collection
          app_name: "prometheus-remotewrite"
          app_namespace: monitoring
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "prometheus-remotewrite"
          app_namespace: monitoring
          app_collection_repo: "capa-app-collection"
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capz-app-collection
          app_name: "prometheus-remotewrite"
          app_namespace: monitoring
          app_collection_repo: "capz-app-collection"
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-gcp-app-collection
          app_name: "prometheus-remotewrite"
          app_namespace: monitoring
          app_collection_repo: "gcp-app-collection"
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
