version: 2.1

orbs:
  architect: giantswarm/architect@6.4.0

jobs:
  template-chart:
    docker:
      - image: giantswarm/helm-chart-testing:v3.13.0
    steps:
      - checkout
      - run: |-
          cd helm/prometheus-remotewrite
          helm dep up
          helm template .

workflows:
  build:
    jobs:
      - template-chart:
          name: "template-chart-test"
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: app-catalog
          context: architect
          executor: app-build-suite
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          chart: prometheus-remotewrite
          ct_config: ".circleci/ct-config.yml"
          persist_chart_archive: true
          requires:
            - "template-chart-test"
          filters:
            tags:
              only: /^v.*/
      
      - architect/run-tests-with-ats:
          name: run-tests-with-ats
          requires:
            - "app-catalog"
          filters:
            branches:
              ignore:
                - main

      - architect/push-to-app-collection:
          name: vsphere-app-collection
          context: architect
          app_name: prometheus-remotewrite
          app_namespace: monitoring
          app_collection_repo: vsphere-app-collection
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-cloud-director-app-collection
          app_name: "prometheus-remotewrite"
          app_namespace: monitoring
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "prometheus-remotewrite"
          app_namespace: monitoring
          app_collection_repo: "capa-app-collection"
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capz-app-collection
          app_name: "prometheus-remotewrite"
          app_namespace: monitoring
          app_collection_repo: "capz-app-collection"
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-proxmox-app-collection
          app_name: "prometheus-remotewrite"
          app_namespace: monitoring
          app_collection_repo: "proxmox-app-collection"
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
